Feature: Pro-Input-Mode for expenses
freshfox/navory pull request #41
Opened 2021-12-22 16:15 UTC by felixjiricka

2021-12-28 12:32 UTC, alexanderott requested changes
Grundsätzlich ist die Umsetzung in Ordnung, allerdings müssen wir uns da in Zukunft vorher besser abstimmen und planen.

Im Idealfall können wir die "Pro" Ansicht problemlos in die existierende ExpensesComponent integrieren und so sehr viel Code wiederverwenden.

Bitte die paar angemerkten Dinge noch anpassen. Dann würde ich es mal mergen und dann langfristig ein Refactoring machen damit wir die Codebasis möglichst sauber halten.

2021-12-28 12:32 UTC, alexanderott commented on webapp/src/app/core/components/document-upload/document-upload.component.html
> +<div class="upload-area dropzone" #uploadArea [class.upload-area--has-file]="isFileUploaded() && !loading" [class.inlineMode]="inlineMode">
CSS Klassen bitte in Kebab Case.

2021-12-28 12:32 UTC, alexanderott commented on webapp/src/app/internal/expenses/expenses-pro.component.html
> +<div class="pro-table-container">
Grundsätzlich in Ordnung, allerdings ist es nicht optimal, dass hier so viel Code dupliziert wurde. Wenn wir das nochmal angreifen dann sollte das in die existierende ExpensesComponent integriert werden.

2021-12-28 12:32 UTC, alexanderott commented on webapp/src/app/i18n/de.json
> +			"description": "Durch die Eingabemaske für Fortgeschrittene lassen sich Ausgaben und sonstige Einnahmen schneller erfassen.",
Bei "sonstigen Einnahmen" gibt es noch keine "Pro Version". Bitte den Text entsprechend anpassen.

2021-12-28 12:32 UTC, alexanderott commented on webapp/src/app/internal/expenses/expenses-pro-preview.component.ts
> +		this.fileService.getFile(this.expense.file.id)
Das File hängt schon an der Expense dran, also muss das nicht nochmal extra geladen werden.

2021-12-28 12:32 UTC, alexanderott commented on webapp/src/app/internal/expenses/expenses-pro.component.ts
> +export class ExpensesProComponent implements OnInit, OnDestroy {
Wenn ich eine Expense anlege kann ich danach keine existierende Expense mehr auswählen.

2021-12-29 18:17 UTC, felixjiricka commented on webapp/src/app/internal/expenses/expenses-pro.component.ts
> +export class ExpensesProComponent implements OnInit, OnDestroy {
Könntest du das vielleicht noch weiter erklären wann genau? Hab es bei mir jetzt mehrere Male ausprobiert: Eine Ausgabe mittels Pro-Input-Maske erstellen, Eingabevorgang mit Button 'Abbrechen' beenden und danach kann eine bestehende Ausgabe ausgewählt und somit bearbeitet, gelöscht werden etc.

2021-12-30 11:00 UTC, alexanderott commented on webapp/src/app/internal/expenses/expenses-pro.component.ts
> +export class ExpensesProComponent implements OnInit, OnDestroy {
Ah ok, ich bin nicht davon ausgegangen, dass ich davor noch "abbrechen" klicken muss. Das sollten wir langfristig noch verbessern, damit für den User klar ist wann er was klicken kann.

2021-12-30 11:02 UTC, merged